[package]
name = "carmine"
version = "0.1.0"
edition = "2024"

[dependencies]
carmine_core = { path = "carmine_core" }
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }

[workspace]
resolver = "3"
members = [
    "carmine_core",
]